language: go
#go_import_path: github.com/codem8s/autograph

go:
  - 1.8
  - 1.x
  - tip
  
env:
  matrix:
   - TARGET=amd64
#   - TARGET=darwin-amd64
#   - TARGET=windows-amd64

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

#before_script:
#  - go get github.com/codem8s/autograph
#  - go get github.com/tools/godep
#  - go get github.com/golang/lint/golint

script:
  - ./pre-commit.sh
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
