language: go

go:
  - 1.8
  - 1.x
  - tip
  
env:
  matrix:
   - TARGET=amd64
#   - TARGET=darwin-amd64
#   - TARGET=windows-amd64

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

before_script:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/golang/lint/golint
  - go get -u golang.org/x/tools/cmd/goimports

script:
  - ./pre-commit.sh
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
