apiVersion: v1
kind: Pod
metadata:
  name: autograph
  namespace: default
  labels:
    app: autograph
spec:
  containers:
    - name: webhook
      image: autograph:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8000
      env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace