apiVersion: v1
kind: Pod
metadata:
  name: autograph
  namespace: default
  labels:
    app: autograph
spec:
  containers:
    - name: autograph
      image: autograph:latest
      command: ["/autograph", "run", "-dir", "/etc/autograph"]
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8000
      volumeMounts:
      - name: autograph
        mountPath: /etc/autograph
  volumes:
  - name: autograph
    secret:
      secretName: autograph