apiVersion: admissionregistration.k8s.io/v1lapha1
kind: ExternalAdmissionHookConfiguration
metadata:
  name: autograph
  namespace: default
spec:
  externalAdmissionHooks:
    - name: pod
      rules:
        - operations:
            - CREATE
          apiGroups:
            - ""
          apiVersions:
            - v1
          resources:
            - pods
      failurePolicy: Fail
      clientConfig:
        service:
          namespace: default
          name: webhook
        caBundle: